#!/bin/bash

# Replace "python3" with your Python interpreter if needed
DS="Heap" 
Operation="Extract" 
cd ..




for itr in $(seq 1 1); do
 for heapsize in $(seq 16 2 26); do
 
 input_file="repro/data/log_basic_heap_extract_online_${heapsize}_itr_${itr}"
 output=$(python3 repro/extract_data.py "$input_file")

 # Read the output into an array
 IFS=$'\n' read -d '' -r -a values <<< "$output"

 # Store each value in different variables
 heapsize=${values[0]}  
 optimization_flag=${values[1]} 
 extract_wc=${values[4]} 
 
 datafile="repro/experimentaldata_wallclock"
 python3 repro/append-experiment-results.py $datafile $DS $Operation $optimization_flag $heapsize $extract_wc

 input_file="repro/data/log_opt_heap_extract_online_${heapsize}_itr_${itr}"
 output=$(python3 repro/extract_data.py "$input_file")

 # Read the output into an array
 IFS=$'\n' read -d '' -r -a values <<< "$output"

 # Store each value in different variables
 heapsize=${values[0]}  optimization_flag=${values[1]} extract_wc=${values[4]}
 datafile="repro/experimentaldata_wallclock"
 python3 repro/append-experiment-results.py $datafile $DS $Operation $optimization_flag $heapsize $extract_wc
 done	
done

cat $datafile
echo -e "\n\n"

for itr in $(seq 1 1); do
  for heapsize in $(seq 16 2 26); do
  input_file="repro/data/log_basic_heap_extract_preproc_${heapsize}_itr_$itr"
  output=$(python3 repro/extract_data_from_preproc.py "$input_file")

  # Read the output into an array
  IFS=$'\n' read -d '' -r -a values <<< "$output"

  # Store each value in different variables
  heapsize=${values[0]}  optimization_flag=${values[1]} preproc_wc=${values[2]} 
  datafile="repro/experimentaldata_preproc_wallclock"
  python3 repro/append-experiment-results.py $datafile $DS $Operation $optimization_flag $heapsize $preproc_wc

  input_file="repro/data/log_opt_heap_extract_preproc_${heapsize}_itr_$itr"
  output=$(python3 repro/extract_data_from_preproc.py "$input_file")

  # Read the output into an array
  IFS=$'\n' read -d '' -r -a values <<< "$output"

  # Store each value in different variables
  heapsize=${values[0]}  optimization_flag=${values[1]} preproc_wc=${values[2]}
  datafile="repro/experimentaldata_preproc_wallclock"
  python3 repro/append-experiment-results.py $datafile $DS $Operation $optimization_flag $heapsize $preproc_wc
 done
done


cat $datafile
echo -e "\n\n"

# Replace "python3" with your Python interpreter if needed
DS="Heap"
Operation="Insert"

for itr in $(seq 1 1); do
  for heapsize in $(seq 16 2 26); do
	 input_file="repro/data/log_basic_heap_insert_online_${heapsize}_itr_$itr"
	 output=$(python3 repro/extract_data.py "$input_file")

	 # Read the output into an array
 	IFS=$'\n' read -d '' -r -a values <<< "$output"
	 # Store each value in different variables
 	heapsize=${values[0]}  optimization_flag=${values[1]}  insert_wc=${values[2]}
	datafile="repro/experimentaldata_wallclock"
 	python3 repro/append-experiment-results.py $datafile $DS $Operation $optimization_flag $heapsize $insert_wc
 	input_file="repro/data/log_opt_heap_insert_online_${heapsize}_itr_$itr"
 	output=$(python3 repro/extract_data.py "$input_file")

	 # Read the output into an array
	 IFS=$'\n' read -d '' -r -a values <<< "$output"
 	# Store each value in different variables
 	heapsize=${values[0]}  optimization_flag=${values[1]}  insert_wc=${values[2]}
 	datafile="repro/experimentaldata_wallclock"
	python3 repro/append-experiment-results.py $datafile $DS $Operation $optimization_flag $heapsize $insert_wc 
  done
done

cat $datafile
echo -e "\n\n"

for itr in $(seq 1 1); do
    for heapsize in $(seq 16 2 26); do	
	 
	input_file="repro/data/log_basic_heap_insert_preproc_${heapsize}_itr_$itr"
 	output=$(python3 repro/extract_data_from_preproc.py "$input_file")
 	# Read the output into an array
 	IFS=$'\n' read -d '' -r -a values <<< "$output"
 	# Store each value in different variables
 	heapsize=${values[0]}  optimization_flag=${values[1]} preproc_wc=${values[2]}
 	datafile="repro/experimentaldata_preproc_wallclock"
 	python3 repro/append-experiment-results.py $datafile $DS $Operation $optimization_flag $heapsize $preproc_wc

 	input_file="repro/data/log_opt_heap_insert_preproc_${heapsize}_itr_$itr"
	 output=$(python3 repro/extract_data_from_preproc.py "$input_file")
	 # Read the output into an array
	 IFS=$'\n' read -d '' -r -a values <<< "$output"
	 # Store each value in different variables
	 heapsize=${values[0]}  optimization_flag=${values[1]} preproc_wc=${values[2]}
	 datafile="repro/experimentaldata_preproc_wallclock"
	 python3 repro/append-experiment-results.py $datafile $DS $Operation $optimization_flag $heapsize $preproc_wc
   done
done
cat $datafile

